GET https://dao-git-alan-dao-111-once-again-figure-out-og-nasafato-s-team.vercel.app/

HTTP 307 
Location: /en/verses/chinese

GET https://dao-git-alan-dao-111-once-again-figure-out-og-nasafato-s-team.vercel.app/
Accept-Language: en-US,en;q=0.9,zh;q=0.7

HTTP 307 
Location: /en/verses/chinese

GET https://dao-git-alan-dao-111-once-again-figure-out-og-nasafato-s-team.vercel.app/
Accept-Language: zh;q=0.9,en-US;q=0.6

HTTP 307 
Location: /zh/verses/chinese
