name = "dao-worker"
main = "src/index.ts"
compatibility_date = "2023-05-04"

account_id = "415f1575d5ed84ec381999efee4b48d7"
workers_dev = true

[[r2_buckets]]
binding = "DAO_BUCKET"
bucket_name = 'daodejing'